package com.gbconnected.catalogs.adapter.postgres;
import com.gbconnected.catalogs.application.DuplicatePlantException; import com.gbconnected.catalogs.application.port.out.PlantRepository; import com.gbconnected.catalogs.domain.Plant;
import java.sql.*; import java.time.Instant; import java.util.*; import javax.sql.DataSource;
public final class JdbcPlantRepository implements PlantRepository {
 private final DataSource ds; public JdbcPlantRepository(DataSource ds){this.ds=Objects.requireNonNull(ds);}
 public Plant insert(Plant p){String sql="INSERT INTO core.plant (organization_id,plant_code,plant_name,erp_plant_code,country_code,region_code,address,timezone_name,language_code,is_active) VALUES (?,?,?,?,?,?,?,?,?,?) RETURNING plant_id,created_at,updated_at";try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement(sql)){bind(s,p);try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalStateException("Insert returned no row");return persisted(p,r.getLong("plant_id"),instant(r,"created_at"),instant(r,"updated_at"));}}catch(SQLException e){throw translate(e,"insert plant");}}
 public Optional<Plant> findAggregateById(long id){String sql="SELECT plant_id,organization_id,plant_code,plant_name,erp_plant_code,country_code,region_code,address,timezone_name,language_code,is_active,created_at,updated_at FROM core.plant WHERE plant_id=?";try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,id);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(map(r)):Optional.empty();}}catch(SQLException e){throw new IllegalStateException("Failed to load plant aggregate",e);}}
 public Plant update(Plant p){String sql="UPDATE core.plant SET organization_id=?,plant_code=?,plant_name=?,erp_plant_code=?,country_code=?,region_code=?,address=?,timezone_name=?,language_code=?,is_active=?,updated_at=CURRENT_TIMESTAMP WHERE plant_id=? RETURNING created_at,updated_at";try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement(sql)){bind(s,p);s.setLong(11,p.id());try(ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalStateException("Plant disappeared during update");return persisted(p,p.id(),instant(r,"created_at"),instant(r,"updated_at"));}}catch(SQLException e){throw translate(e,"update plant");}}
 public boolean delete(long id){try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement("DELETE FROM core.plant WHERE plant_id=?")){s.setLong(1,id);return s.executeUpdate()>0;}catch(SQLException e){throw new IllegalStateException("Failed to delete plant. It may still be referenced by other records.",e);}}
 private void bind(PreparedStatement s,Plant p)throws SQLException{s.setLong(1,p.organizationId());s.setString(2,p.plantCode());s.setString(3,p.plantName());s.setString(4,p.erpPlantCode());s.setString(5,p.countryCode());s.setString(6,p.regionCode());s.setString(7,p.address());s.setString(8,p.timezoneName());s.setString(9,p.languageCode());s.setBoolean(10,p.active());}
 private RuntimeException translate(SQLException e,String op){if("23505".equals(e.getSQLState()))return new DuplicatePlantException("A plant with the same organizationId and plantCode already exists",e);return new IllegalStateException("Failed to "+op,e);}
 private Plant map(ResultSet r)throws SQLException{return Plant.rehydrate(r.getLong("plant_id"),r.getLong("organization_id"),r.getString("plant_code"),r.getString("plant_name"),r.getString("erp_plant_code"),r.getString("country_code"),r.getString("region_code"),r.getString("address"),r.getString("timezone_name"),r.getString("language_code"),r.getBoolean("is_active"),instant(r,"created_at"),instant(r,"updated_at"));}
 private Plant persisted(Plant p,long id,Instant created,Instant updated){return Plant.rehydrate(id,p.organizationId(),p.plantCode(),p.plantName(),p.erpPlantCode(),p.countryCode(),p.regionCode(),p.address(),p.timezoneName(),p.languageCode(),p.active(),created,updated);}
 private Instant instant(ResultSet r,String c)throws SQLException{Timestamp t=r.getTimestamp(c);return t==null?null:t.toInstant();}
}
