package com.gbconnected.catalogs.adapter.postgres;
import com.gbconnected.catalogs.application.port.out.*; import com.gbconnected.catalogs.application.query.*;
import java.sql.*; import java.time.Instant; import java.util.*; import javax.sql.DataSource;
public final class JdbcCatalogQueryAdapter implements OrganizationQueryPort,PlantQueryPort,DatabaseHealthPort {
 private final DataSource ds; public JdbcCatalogQueryAdapter(DataSource ds){this.ds=Objects.requireNonNull(ds);}
 public List<OrganizationSummary> findAll(Boolean active){String sql="SELECT organization_id, organization_code, organization_name, is_active, created_at, updated_at FROM core.organization"+(active==null?"":" WHERE is_active = ?")+" ORDER BY organization_name"; try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement(sql)){if(active!=null)s.setBoolean(1,active);try(ResultSet r=s.executeQuery()){List<OrganizationSummary>x=new ArrayList<>();while(r.next())x.add(org(r));return List.copyOf(x);}}catch(SQLException e){throw new IllegalStateException("Failed to list organizations",e);}}
 public Optional<OrganizationSummary> findOrganizationById(long id){String sql="SELECT organization_id, organization_code, organization_name, is_active, created_at, updated_at FROM core.organization WHERE organization_id=?";try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,id);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(org(r)):Optional.empty();}}catch(SQLException e){throw new IllegalStateException("Failed to query organization",e);}}
 public List<PlantSummary> findAll(Long organizationId,Boolean active){StringBuilder sql=new StringBuilder("SELECT plant_id, organization_id, plant_code, plant_name, erp_plant_code, country_code, region_code, address, timezone_name, language_code, is_active, created_at, updated_at FROM core.plant");List<Object>p=new ArrayList<>();if(organizationId!=null||active!=null){sql.append(" WHERE ");if(organizationId!=null){sql.append("organization_id=?");p.add(organizationId);}if(active!=null){if(!p.isEmpty())sql.append(" AND ");sql.append("is_active=?");p.add(active);}}sql.append(" ORDER BY plant_name");try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement(sql.toString())){for(int i=0;i<p.size();i++)s.setObject(i+1,p.get(i));try(ResultSet r=s.executeQuery()){List<PlantSummary>x=new ArrayList<>();while(r.next())x.add(plant(r));return List.copyOf(x);}}catch(SQLException e){throw new IllegalStateException("Failed to list plants",e);}}
 public Optional<PlantSummary> findPlantById(long id){String sql="SELECT plant_id, organization_id, plant_code, plant_name, erp_plant_code, country_code, region_code, address, timezone_name, language_code, is_active, created_at, updated_at FROM core.plant WHERE plant_id=?";try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement(sql)){s.setLong(1,id);try(ResultSet r=s.executeQuery()){return r.next()?Optional.of(plant(r)):Optional.empty();}}catch(SQLException e){throw new IllegalStateException("Failed to query plant",e);}}
 public void check(){try(Connection c=ds.getConnection();PreparedStatement s=c.prepareStatement("SELECT 1");ResultSet r=s.executeQuery()){if(!r.next())throw new IllegalStateException("Database health query returned no row");}catch(SQLException e){throw new IllegalStateException("Database health check failed",e);}}
 private OrganizationSummary org(ResultSet r)throws SQLException{return new OrganizationSummary(r.getLong("organization_id"),r.getString("organization_code"),r.getString("organization_name"),r.getBoolean("is_active"),instant(r,"created_at"),instant(r,"updated_at"));}
 private PlantSummary plant(ResultSet r)throws SQLException{return new PlantSummary(r.getLong("plant_id"),r.getLong("organization_id"),r.getString("plant_code"),r.getString("plant_name"),r.getString("erp_plant_code"),r.getString("country_code"),r.getString("region_code"),r.getString("address"),r.getString("timezone_name"),r.getString("language_code"),r.getBoolean("is_active"),instant(r,"created_at"),instant(r,"updated_at"));}
 private Instant instant(ResultSet r,String c)throws SQLException{Timestamp t=r.getTimestamp(c);return t==null?null:t.toInstant();}
}
