-- Local-only dependency so the Users microservice can be exercised by itself.
-- In shared environments these tables are owned by the Catalogs bounded context.
CREATE SCHEMA IF NOT EXISTS core;
CREATE TABLE IF NOT EXISTS core.organization (
    organization_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    organization_code varchar(50) NOT NULL UNIQUE,
    organization_name varchar(200) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS core.plant (
    plant_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    organization_id bigint NOT NULL REFERENCES core.organization(organization_id),
    plant_code varchar(50) NOT NULL,
    plant_name varchar(200) NOT NULL,
    erp_plant_code varchar(100), country_code varchar(20), region_code varchar(50), address varchar(500),
    timezone_name varchar(100) NOT NULL, language_code varchar(20), is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_plant_org_code UNIQUE (organization_id, plant_code)
);
INSERT INTO core.organization(organization_id,organization_code,organization_name,is_active) VALUES (1,'MX','Organización México',true) ON CONFLICT DO NOTHING;
INSERT INTO core.plant(plant_id,organization_id,plant_code,plant_name,country_code,timezone_name,language_code,is_active) VALUES
(1,1,'TOL','Planta Toluca','MX','America/Mexico_City','es-MX',true),
(2,1,'PUE','Planta Puebla','MX','America/Mexico_City','es-MX',true)
ON CONFLICT DO NOTHING;
