CREATE SCHEMA IF NOT EXISTS core;

CREATE TABLE IF NOT EXISTS core.organization (
    organization_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    organization_code varchar(50) NOT NULL UNIQUE,
    organization_name varchar(200) NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS core.plant (
    plant_id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    organization_id bigint NOT NULL,
    plant_code varchar(50) NOT NULL,
    plant_name varchar(200) NOT NULL,
    erp_plant_code varchar(100),
    country_code varchar(20),
    region_code varchar(50),
    address varchar(500),
    timezone_name varchar(100) NOT NULL,
    language_code varchar(20),
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT uq_plant_org_code UNIQUE (organization_id, plant_code),
    CONSTRAINT plant_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES core.organization(organization_id)
);
