-- ============================================================
-- PROPUESTA DE ADECUACIÓN
-- ORGANIZATION -> REGION -> COUNTRY -> PLANT
--
-- Se conservan temporalmente en core.plant:
--   organization_id
--   region_code
--   country_code
--
-- para no romper la estructura actual durante la migración.
-- ============================================================


-- ============================================================
-- 1. NUEVA TABLA: REGION
-- ============================================================
CREATE TABLE core.region (
    region_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    organization_id BIGINT NOT NULL,

    parent_region_id BIGINT,

    region_code VARCHAR(50) NOT NULL,

    region_name VARCHAR(150) NOT NULL,

    display_order INTEGER,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_region_organization
        FOREIGN KEY (organization_id)
        REFERENCES core.organization (organization_id),

    CONSTRAINT fk_region_parent
        FOREIGN KEY (parent_region_id)
        REFERENCES core.region (region_id),

    CONSTRAINT uq_region_org_code
        UNIQUE (organization_id, region_code),

    CONSTRAINT ck_region_not_self_parent
        CHECK (
            parent_region_id IS NULL
            OR parent_region_id <> region_id
        )
);


CREATE INDEX idx_region_organization
    ON core.region (organization_id);

CREATE INDEX idx_region_parent
    ON core.region (parent_region_id);

CREATE INDEX idx_region_active
    ON core.region (is_active);



-- ============================================================
-- 2. NUEVA TABLA: COUNTRY
-- Catálogo global de países.
-- ============================================================

CREATE TABLE core.country (
    country_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    country_code VARCHAR(3) NOT NULL,

    country_name VARCHAR(150) NOT NULL,

    iso_alpha2 VARCHAR(2),

    iso_alpha3 VARCHAR(3),

    display_order INTEGER,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_country_code
        UNIQUE (country_code),

    CONSTRAINT uq_country_iso_alpha2
        UNIQUE (iso_alpha2),

    CONSTRAINT uq_country_iso_alpha3
        UNIQUE (iso_alpha3)
);


CREATE INDEX idx_country_active
    ON core.country (is_active);



-- ============================================================
-- 3. NUEVA TABLA: REGION_COUNTRY
--
-- Permite relacionar un mismo país con distintas regiones
-- según la organización/configuración de negocio.
-- ============================================================

CREATE TABLE core.region_country (
    region_country_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    region_id BIGINT NOT NULL,

    country_id BIGINT NOT NULL,

    display_order INTEGER,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_region_country_region
        FOREIGN KEY (region_id)
        REFERENCES core.region (region_id),

    CONSTRAINT fk_region_country_country
        FOREIGN KEY (country_id)
        REFERENCES core.country (country_id),

    CONSTRAINT uq_region_country
        UNIQUE (region_id, country_id)
);


CREATE INDEX idx_region_country_region
    ON core.region_country (region_id);

CREATE INDEX idx_region_country_country
    ON core.region_country (country_id);

CREATE INDEX idx_region_country_active
    ON core.region_country (is_active);



-- ============================================================
-- 4. ADECUACIÓN DE CORE.PLANT
--
-- Se agrega la nueva relación REGION -> COUNTRY -> PLANT.
-- NO se eliminan todavía:
--      organization_id
--      region_code
--      country_code
-- ============================================================

ALTER TABLE core.plant
    ADD COLUMN region_country_id BIGINT;


ALTER TABLE core.plant
    ADD CONSTRAINT fk_plant_region_country
        FOREIGN KEY (region_country_id)
        REFERENCES core.region_country (region_country_id);


CREATE INDEX idx_plant_region_country
    ON core.plant (region_country_id);
